version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=root
    volumes:
      - ./src/app/data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=w@admin.com
     - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres

  node-app:
    build:
      context: .
      dockerfile: ./src/Dockerfile  
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
